IMDB-BINARY:
  lr: 0.00015
  lr_f: 0.005
  num_hidden: 512
  num_heads: 2
  weight_decay: 0
  weight_decay_f: 0
  max_epoch: 50
  max_epoch_f: 500
  mask_rate: 0.3
  num_layers: 1
  encoder: gin
  decoder: gin
  activation: prelu
  in_drop: 0.2
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.05
  drop_edge_rate: 0.0
  norm: batchnorm
  residual: False
  scheduler: False
  linear_prob: True
  pooling: mean_max
  batch_size: 32
  alpha_l: 1
IMDB-MULTI:
  lr: 0.00015
  num_hidden: 512
  num_heads: 2
  weight_decay: 0
  max_epoch: 50
  mask_rate: 0.3
  num_layers: 1
  encoder: gin
  decoder: gin
  activation: prelu
  in_drop: 0.2
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.05
  drop_edge_rate: 0.0
  alpha_l: 1
  norm: batchnorm
  scheduler: False
  linear_prob: True
  pooling: mean
  batch_size: 32
  pe_dim: 10
PROTEINS:
  lr: 0.00015
  num_hidden: 512
  weight_decay: 0
  max_epoch: 100
  num_layers: 3
  encoder: gin
  decoder: gin
  activation: prelu
  in_drop: 0.2
  loss_fn: sce
  optimizer: adam
  mask_rate: 0.6
  drop_edge_rate: 0.0
  replace_rate: 0.05
  alpha_l: 1
  norm: batchnorm
  scheduler: False
  linear_prob: True
  pooling: max
  batch_size: 32
REDDIT-BINARY:
  lr: 0.006
  weight_decay: 0.0
  num_heads: 4
  max_epoch: 100
  mask_rate: 0.6
  drop_edge_rate: 0.0
  num_hidden: 512
  num_layers: 2
  encoder: gcn
  decoder: gcn
  activation: prelu
  pooling: max
  scheduler: False
  batch_size: 8
  replace_rate: 0.1
  norm: layernorm
  loss_fn: sce
  alpha_l: 1
COLLAB:
  lr: 0.00015
  weight_decay: 0.0
  max_epoch: 20
  num_layers: 1
  num_hidden: 512
  mask_rate: 0.5
  replace_rate: 0.05
  drop_edge_rate: 0.0
  activation: relu
  encoder: gin
  decoder: gin
  scheduler: True
  pooling: max
  batch_size: 32
  loss_fn: sce
  norm: batchnorm
  alpha_l: 1
NCI1:
  lr: 0.0001
  max_epoch: 300
  num_layers: 3
  num_hidden: 512
  mask_rate: 0.25
  drop_edge_rate: 0.0
  activation: prelu
  encoder: gin
  decoder: gin
  scheduler: True
  pool: sum
  batch_size: 16
  alpha_l: 2
  replace_rate: 0.1
  norm: batchnorm
  loss_fn: sce
DD:
  lr: 0.00015
  num_hidden: 512
  weight_decay: 0
  max_epoch: 100
  mask_rate: 0.3
  num_layers: 1
  encoder: gin
  decoder: gin
  activation: prelu
  in_drop: 0.2
  loss_fn: sce
  optimizer: adam
  drop_edge_rate: 0.0
  alpha_l: 1
  replace_rate: 0.05
  norm: batchnorm
  scheduler: False
  linear_prob: True
  pooling: max
  batch_size: 32
